// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCItFSwEBbPXgH-FZPsbNQ-g9imwCe4Grk',
    appId: '1:691255811403:web:fb0f5a7be02ee599bddcce',
    messagingSenderId: '691255811403',
    projectId: 'reddit-clone-tutorial-1388f',
    authDomain: 'reddit-clone-tutorial-1388f.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-1388f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnrvSQTAAtVWAn__5jdmIdqaM_wNoj4rc',
    appId: '1:691255811403:android:f4ac247b2f32999bbddcce',
    messagingSenderId: '691255811403',
    projectId: 'reddit-clone-tutorial-1388f',
    storageBucket: 'reddit-clone-tutorial-1388f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk0U6l-idSYUYpZuI4GDBZkU9u_TmuzWk',
    appId: '1:691255811403:ios:0ae94dde00e5c7f4bddcce',
    messagingSenderId: '691255811403',
    projectId: 'reddit-clone-tutorial-1388f',
    storageBucket: 'reddit-clone-tutorial-1388f.appspot.com',
    iosClientId: '691255811403-o2933oeo08dsv3h49ohk8ioridnbjae9.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
